Repository PatchiPup/Jarvis-Mark-II, pull requests merged in 2025-03, with the labels that each got.

#8 Localization
  CHANGELOG.MD
  README.MD
  audio.py
  chat.py
  command_modules/music_module.py
  command_modules/obs_module.py
  command_modules_init.py
  config.ini
  config.py
  exit.py
  locales/en/LC_MESSAGES/messages.mo
  locales/en/LC_MESSAGES/messages.po
  locales/es/LC_MESSAGES/messages.mo
  locales/es/LC_MESSAGES/messages.po
  locales/fr/LC_MESSAGES/messages.mo
  locales/fr/LC_MESSAGES/messages.po
  locales/pt/LC_MESSAGES/messages.mo
  locales/pt/LC_MESSAGES/messages.po
  locales/setup_messages.json
  locales/system_instructions.json
  localization.py
  main.py
  setup.bat
  start.bat
Labels: documentation, enhancement

#10 Voicemeeter/VB-Cable Support & Auto Updater
  CHANGELOG.MD
  audio.py
  config.ini
  config.py
  locales/en/LC_MESSAGES/messages.mo
  locales/en/LC_MESSAGES/messages.po
  locales/es/LC_MESSAGES/messages.mo
  locales/es/LC_MESSAGES/messages.po
  locales/fr/LC_MESSAGES/messages.mo
  locales/fr/LC_MESSAGES/messages.po
  locales/pt/LC_MESSAGES/messages.mo
  locales/pt/LC_MESSAGES/messages.po
  locales/setup_messages.json
  localization.py
  main.py
  setup.bat
  start.bat
  updater.py
Labels: enhancement

#11 Bug fixes from Discord
  README.MD
  command_modules/main_module.py
  command_modules/obs_module.py
  config.ini
  config.py
Labels: bug, enhancement

#14 Spotify Module + Interrupt Jarvis Feature
  CHANGELOG.MD
  README.MD
  audio.py
  command_modules/main_module.py
  command_modules/spotify_module.py
  command_modules_init.py
  config.ini
  config.py
  main.py
  requirements.txt
Labels: enhancement

#17 Macro Module
  CHANGELOG.MD
  README.MD
  command_modules/macro_module.py
  commands.py
  config.ini
  config.py
  personalities/friday.json
  personalities/karen.json
  personalities/ultron.json
Labels: enhancement

#18 Faster Whisper Support & Bug Fixes
  CHANGELOG.MD
  README.MD
  audio.py
  command_modules/macro_module.py
Labels: enhancement

#19 Small Bug Fixes/Features
  README.MD
  command_modules/macro_module.py
  config.ini
  config.py
  personality.py
  sounds/ultron.mp3
Labels: bug

#20 Fix git issue with setup script that required running the script again after git install
  setup.bat
Labels: bug

#21 Minor changes/fixes
  README.MD
  setup.bat
Labels: documentation

#22 Bug Fixes
  command_modules/main_module.py
  setup.bat
Labels: bug
